version: '3'

services:
  db:
    image: mysql
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=url_shortener
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/opt/backend
    ports:
      - 3001:3000
  
  client:
    container_name: client
    build:
      context: ./client
    depends_on:
      - backend
    volumes:
      - ./client/src:/opt/client/src

    ports:
      - 3000:3000